FROM node:22-alpine AS build
WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=http://localhost:5202
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build

FROM busybox:1.37.0-uclibc AS final

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 4173

ENTRYPOINT ["busybox", "httpd", "-f", "-p", "4173", "-h", "/usr/share/nginx/html"]
